---
title: "p8105_hw5_fc2691"
author: "FC"
date: "11/15/2021"
output: html_document
---
## Problem 1  
```{r message = FALSE}
library(readr)
library(tidyverse)
library(knitr)
library(rvest)
library(broom)
library(dplyr)
library(fs)

url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homi_data <- read_csv(url(url), na = c("", "Unknown"))
```
There are total `r ncol(homi_data)` variables and `r nrow(homi_data)` observations in this raw file. It describes each incidents in details with the time, location, the offenders' personal information and the arrest results.  

```{r message = FALSE}
# Clean data of homicides
homi_data_raw <-
  homi_data %>% 
  # mutate(city_state = str_c(city, ", ", state))
  mutate(city_state = paste(city, state, sep = ", ")) %>% 
  relocate(city_state) %>% 
  mutate(
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest" ~ "unsolved", 
      disposition == "Closed by arrest" ~ "solved"
  )) %>% 
  filter(city_state != "Tulsa, AL")
# Summarize total number of homicides in cities. 
homi_city_count <- 
  homi_data_raw %>% 
  count(city_state) %>% 
  rename(homi_count = n)

# Count number of unsolved homicides. 
homi_unsol_count <- 
  homi_data_raw %>% 
  filter(resolution == "unsolved") %>%
  count(city_state) %>% 
  rename(unsol_count = n)
# Joint table of total counts of homicides and unsolved homicides. 
homi_joint_count = left_join(homi_city_count, homi_unsol_count, by = "city_state")
kable(homi_joint_count)

# Focus on Baltimore, MD
baltimore_df <- 
  homi_data_raw %>% 
  filter(city_state == "Baltimore, MD") %>% 
  summarize(unsolved_n = sum(resolution == "unsolved"), 
            total_n = n()) 

# prop.test("Baltimore, MD")
baltimore_test <- 
  prop.test(baltimore_df$unsolved_n, baltimore_df$total_n)
# prop.test(baltimore_df %>% pull(unsolved_n), baltimore_df %>% pull(total_n))

baltimore_test %>% 
  broom::tidy()

# Write function-test across several cities
prop_test_function <- function(city_df) {
  city_summary <-
    city_df %>% 
    summarize(
      unsolved_n = sum(resolution == "unsolved"), 
      total_n = n()
    ) 
  city_test <- 
    prop.test(
      city_summary$unsolved_n, 
      city_summary$total_n)
  
  return(city_test)
}

balti_df <- 
  homi_data_raw %>% 
  filter(city_state == "Baltimore, MD") 
prop_test_function(balti_df)

homi_data_raw %>% 
  filter(city_state == "Albuquerque, NM") %>% 
  prop_test_function()

# Iterate across all cities
results_df <-
  homi_data_raw %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    city_test = map(data, prop_test_function),
    tidy_results = map(city_test, broom::tidy)
  ) %>% 
  dplyr::select(city_state, tidy_results) %>%
  unnest(tidy_results) %>% 
  dplyr::select(city_state, estimate, starts_with("conf"))

# Code above learned from OH using function. 
# # Run prop.test for all cities
# city_df <- 
#   homi_data_raw %>% 
#   group_by(city_state) %>% 
#   summarize(unsolved_n = sum(resolution == "unsolved"), 
#             total_n = n()) 
# 
# city_test <- city_df %>%
#   mutate(
#     city_test = purrr::map2(unsolved_n, total_n, prop.test),
#     city_test = purrr::map(city_test, tidy)
#   ) %>%
#   unnest(city_test) %>% 
#   dplyr::select(city_state, estimate, conf.low, conf.high)


# Create plots for each city
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2
```{r}
# # Data frame containing all files names.
file_list <-
  tibble(files = list.files("./data")) 

# Map data
file_df_raw <- 
  file_list %>% 
  mutate(
    file_path = paste("./data", files, sep = '/'),
    file_content = map(file_path, read_csv)
  ) %>%
  unnest(file_content)

# Clean data
file_df_clean <-
  file_df_raw %>% 
  select(-file_path) %>% 
  mutate(files = sub(".csv", "", files)) %>%
  separate(files, into = c("control_arm", "subject_ID"), sep = "_") %>%
  pivot_longer(
    week_1:week_8,
    names_to = "week_id", 
    values_to = "data")
file_df_clean

# Make a spahetti plot. 
obs_vis_plot = 
  file_df_clean %>% 
  ggplot(aes(x = week_id, y = data)) +
    geom_violin(fill = "grey", color = "grey") +
    theme_classic() +
    theme(legend.position = "bottom")
obs_vis_plot

```

## Problem 3
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

# Build missing function
fill_in_missing <- function(vector) {
  if (is.numeric(vector)) {
    vector = ifelse(is.na(vector), mean(vector, na.rm = TRUE), vector)
  }
  if (is.character(vector)) {
    vector = ifelse(is.na(vector), "virginica", vector)
  }
  else {
    vector = ifelse(is.na(vector), "ERROR", vector)
  }
}
iris_no_missing <- map_dfr(iris_with_missing, fill_in_missing)
iris_no_missing
```

